apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tenant-operator
  template:
    metadata:
      labels:
        name: tenant-operator
    spec:
      containers:
        - name: tenant-operator
          image: rekcah/tenant-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - tenant-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "tenant-operator"
